### ISSUE TITLE
about the loss weights

### ISSUE THREAD

**Issue by jinganglang567** [zhanglijun95/ZoDiac#3]
sorry to bother you doctor , i have a question about the loss_weight in config,yaml, The initial value should be set to how much

**Comment by zhanglijun95** [comment]
You can directly use the weights set in the example config.yaml.

**Comment by jinganglang567** [comment]
sorry to bother you doctor again , i have a question about the loss_weight in config,yaml, The initial value is loss_weights: [10.0, 0.1, 1.0, 0.0], i want to konw you why the lossw weight is zero

**Comment by zhanglijun95** [comment]
This is because in every iteration, we add the watermark again into the latent vector so that the watermark is always there and you don't need the loss weights to constrain it anymore. Initially, we train the latent vector without fixing the watermark part in every iteration. It works but may influence the watermark robustness during training, so we switched to the current version. We keep the loss weight here just for clearance.

**Comment by jinganglang567** [comment]
thank you doctor
