### ISSUE TITLE
can this publicly available code be used to test the xl-base-1.0 model?

### ISSUE THREAD

**Issue by annpion** [zhanglijun95/ZoDiac#5]
The paper references the xl-base-1.0 model, can this publicly available code be used to test the xl-base-1.0 model?
I had this error in my testing
![image](https://github.com/user-attachments/assets/4640aabc-33c8-409b-bf11-273c5dd6f12b)

**Comment by zhanglijun95** [comment]
Hi there, the current code is not compatible with xl-base-1.0 model because XL is the StableDiffusionXLPipeline instead of StableDiffusionPipeline. So you need to implement a new WatermarkStableDiffusionPipeline and WMDetectStableDiffusionPipeline following the two classes in wmdiffusion.py. Specifically, the new classes should inherit from StableDiffusionXLPipeline, which follows the [Huggingface](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L175) implementation.
